export default {
    about: 'About SunMae',
    product: 'Product Center',
    service: 'Service Center',
    download: 'Download Center',
    concact: 'Contact us',
    support: "Technical support: Jiangsu Snowball Software",
    follow_us: "Follow us",
    company_address: "No. 6, Longhu East Road, Economic and Technological Development Zone, Xuzhou City, Jiangsu Province",
    componany_controducation: "Company Profile",
    all_world: "Global Distribution",
    news_center: 'Enterprise Dynamics',
    guangfu_power: 'Photovoltaic power station',
    power_system: 'Energy storage system',
    sun_no_limit: "Solar innovation, energy without boundaries",
    no_limit_tomorrow: "Driven by innovative technology, leading the solar energy revolution and creating a tomorrow with unlimited energy",
    know_xm: 'Understanding SunMae',
    sun_with: "Smart energy, accompanied by the sun",
    sun_road: "On the road to sustainable development, let smart energy serve as the guide and let the sun's light accompany you forever.",
    know_gfdz: "Understanding photovoltaic power plants",
    feture_solution: "Energy Storage for the Future: Providing Innovative Solutions to Energy Challenges",
    feture_solution_sub: "Evolution of energy storage technology: from batteries to thermal storage, multiple choices lead the energy revolution",
    know_cnxt: 'Learn about energy storage systems',
    settle_servie: "Customized solutions, enjoy quality service",
    settle_servie_sub: "Harness the power of the sun to create a green energy future tailored for you",
    settle_servie_btn: "Learn about services",
    key_feture: "Database, the key to discovering the energy future",
    key_feture_sub: "Through data insights, reveal the wisdom code that leads the door to future energy",
    key_feture_btn: "Download Center",
    create_way: "Communication and Cooperation: Connecting the Road to Energy Innovation",
    create_way_sub: "The professional team provides you with personalized services. You can contact us through the following methods",
    create_way_btn: "contact us",
    ten_year: 'Over ten years',
    experise: "experience",
    one_wish: "a vision",
    Mwall: 'Megawatt',
    amount_machain: "Total installed capacity",
    company_intro: "Company Profile",
    first_intro: "Jiangsu SunMae Photovoltaic Technology Co., Ltd. is affiliated to C&S IKE Group and was established in 2017. The company is headquartered in Xuzhou City, Jiangsu Province, the core city of the Huaihai Economic Zone. The company focuses on the global development, investment, construction and operation of photovoltaic power stations and energy storage projects Maintenance management, integrating the strong support of parent company C&S IKE Group, is committed to the construction of distributed photovoltaic power stations and energy storage, contributing to the global energy revolution and green city construction.",
    second_intro: 'Team members have accumulated more than 10 years of industry experience and master the essence of photovoltaic power stations and energy storage projects. Relying on exquisite design, efficient construction and excellent post-operation and maintenance, we ensure that each photovoltaic power station and energy storage project continues to operate efficiently. ',
    thirs_intro: "Our vision is to present efficient, safe green power to the world and create excellent returns for our partners",
    forward: "leading",
    high_product: "High Performance Products",
    one_body: 'Integration',
    poduct_map: "Industrial Distribution",
    gf_expreise: "Photovoltaic Industry Experience",
    authority: "authority",
    responity_sg: "Construction Qualification Guarantee",
    fast: "fast",
    recall_service: "Response Service",
    global_map: "Global layout",
    blobal_details: 'Jiangsu SunMae Photovoltaic Technology Co., Ltd.has strong strength.Relying on the strong capital and technical advantages of C & S IKE Group Company.The business covers more than 30 countries and regions, among which the company has established companies in Greece, Europe, Shanghai, Xuzhou, Hefei and Tianjin, China. ',
    partener: "Partner",
    news_desc: "The latest developments or news officially released by SunMae, providing you with first-hand information about SunMae Photovoltaics",
    investment_value: "investment value",
    investment_value_content: "Multiple benefits such as electricity discounts, electricity sales income, policy subsidies, and carbon trading, high profits and high returns",
    safe_reliable: "Safe and reliable",
    safe_reliable_content: "Contribute tax revenue to the local government, provide employment for local people, and bring land income to local people",
    power_rationing: "Easing power cuts",
    power_rationing_content: "While alleviating the power shortage problem of high energy-consuming enterprises, it also effectively avoids the resource waste and power limitation problems that centralized power stations ofen  face",
    emission_reduction: "Environmental protection and emission reduction",
    emission_reduction_content: "1MW distributed power generation is about 1.1 million kilowatt-hours per year, which is equivalent to saving 350 tons of standard coal and reducing carbon dioxide emissions by 1,000 tons.",
    energie_trends: "Energy Trends",
    energie_trends_content: "The trend of solving global energy and carbon emission problems, the advantages of green supply chain management in the international trade environment",
    stable_electricity: "Stable electricity consumption",
    stable_electricity_content: "Effectively avoids the possible negative impact of future increases in electricity prices, providing strong support for the company's production operations and financial health.",
    gfdz_intro: "A photovoltaic power station is a facility that uses solar photovoltaic technology to generate electricity on a large scale. It usually consists of a large number of solar panels used to convert sunlight into electrical energy. These panels convert solar energy into DC current through the photovoltaic effect, and then pass through The inverter converts AC power so that it can be connected to the power network to supply energy. Photovoltaic power plants play an important role in the energy field and can provide society with clean, renewable electricity, reduce dependence on fossil fuels, reduce greenhouse gas emissions, and promote The realization of sustainable development and environmental protection goals.",
    installed_area: "Installed region",
    partener_company: 'partner company',
    storage: "storage",
    storage_subtitle: "fully integrated",
    watch_day: "reliable",
    watch_day_subtitle: "24/7 monitoring",
    soft_control: "Mobile terminal",
    soft_control_subtitle: "Software Control",
    power_system_intro: "An energy storage system is a facility that converts and stores excess solar power for use when solar power is unavailable or power demand peaks. These energy storage systems help solve the intermittent characteristics of photovoltaic power generation, allowing solar power to Provide more stable supply to users and improve energy efficiency. Such a system can make photovoltaic power generation more reliable while reducing dependence on traditional power grids. Energy storage systems can also release power during peak power demand to help balance power supply and demand. , reduce energy waste.",
    max_value: "Maximizing value",
    max_value_intro: "Secure and grow your business with responsibly sourced, lower-cost, self-optimizing software systems. Generate and store sustainable energy for ready use during peak demand or utility grid outages.",
    product_special: "Features",
    product_special_content: "Designed for utility and large-scale commercial projects. Our team of professionals will help you design a system that meets your project goals while maximizing your site's potential.",
    product_special1: "Peak load suppression",
    product_special1_content: "Power supply during peak periods can reduce costs",
    product_special2: "solar energy self-consumption",
    product_special2_content: "Using stored solar energy to power businesses at night",
    product_special3: "Electrical Load Conversion",
    product_special3_content: "Shift energy consumption from one point in time to another to avoid paying high prices",
    product_special4: "Public Grid Services",
    product_special4_content: "Providing frequency and voltage support to the grid",
    product_special5: "Demand Response",
    product_special5_content: "Earn money by responding to utility signals when energy demand is high",
    product_special6: "Microgrid",
    product_special6_content: "Energy can be generated, stored and managed with or without a grid connection",
    product_special7: "backup power",
    product_special7_content: "Using stored energy to provide power for operations when the utility grid is out",
    service_content: "The company has a leading photovoltaic technology team, experienced professionals, and an extensive global presence to provide customers with excellent technical services and is committed to providing customers with comprehensive photovoltaic solutions and high-quality after-sales support. Whether in photovoltaic power plants In the development, construction, operation and maintenance, or in the planning and implementation of energy storage projects, we use our professional knowledge and solid technology to provide customers with long-lasting and reliable services, and provide solid support for customers to achieve sustainable development.",
    watch_day_subtitle_content: "We are proud of our photovoltaic technology team, which consists of top industry experts and experienced engineering personnel. With billions of hours of safe operation records, we ensure that our battery systems maintain the highest standards in every aspect from transportation to installation. With excellent reliability and security. In order to ensure that customers always receive the best quality service, we have set up a network operation center to provide 24/7 monitoring to ensure the efficient operation of power stations and energy storage projects.",
    check_anytime: "Check anytime on APP",
    check_anytime_content: "The monitoring system we provide not only allows you to check project information at any time through the computer, but also provides you with the convenience of anytime and anywhere through the mobile app. No matter where you are, you can just open the mobile app to monitor and control in real time. Master the project running status, obtain data analysis and performance indicators, and provide comprehensive real-time monitoring and management of your photovoltaic power stations and energy storage projects to ensure that you are always aware of the dynamics of the project, thereby managing your energy resources more flexibly and intelligently. ",
    hot_line: "Infrared thermal image of power station",
    hot_line_content1: "China's photovoltaic industry is developing very rapidly in the international market. As a kind of clean energy, the prospects of the photovoltaic industry are immeasurable. But at the same time, there are also many problems. There will be quality hazards or safety hazards during the operation of photovoltaic power stations, and accidents will occur. As an accurate, fast and reliable solar panel inspection tool, the infrared thermal imaging camera can comprehensively monitor the system status and help photovoltaic power stations solve fault problems. Our company specially purchased the DJI Mavic 3T worry-free set to solve this problem. Through optimization Color pixel distribution and IREdge detail-enhanced imaging can enhance the sharpness of image lines and make the outline of photovoltaic modules clearer. Visible light temperature measurement technology looks at the thermal image while comparing the measured object to confirm the actual location of the defect.",
    hot_line_content2: "By adjusting the transparency of the thermal image, the temperature data at any point can be obtained in the visual state of the visible light photo, which is very friendly and convenient for operation and maintenance personnel to observe and analyze defects.",
    sys_authority: "Institutional Certification",
    sys_authority_content1: "IEC61701,IEC62716, IEC60068",
    sys_authority_content2: "IS09001: 2015: Quality Management System IS014001: 2015: Environmental Management System",
    sys_authority_content3: "IS045001: 2018: Occupational Health and Safety Management System",
    download_desc: "You can find documentation on the technical and credit sections of the collection list for more information",
    concact_desc: "You can contact SunMae Photovoltaics through the following methods",
    table_number: "serial number",
    material_name: "Material name",
    material_type: "material type",
    material_use: "Description/Use",
    main_company: "China Company Headquarters",
    main_company_name: "Jiangsu SunMae Photovoltaic Technology Co., Ltd.",
    main_company_address: "Jinlong Lake Innovation Valley, No. 6 Longhu East Road, Xuzhou Economic Development Zone, Jiangsu Province",
    other_company1: 'parent company',
    other_company1_name: 'WANG O.E. "ELECTRIC POWER PATRAS"',
    other_company1_address: 'N.E.O. Patron - Athinon 74, Patra 264 42',
    other_company2: 'Shanghai Branch',
    other_company2_name: 'Shanghai Basik Energy Technology Co., Ltd.',
    other_company2_address: 'Bay Valley Science and Technology Park, Lane 1688, Guoquan North Road, Yangpu District, Shanghai',
    other_company3: 'Tianjin Branch',
    other_company3_name: 'Xineng Electric Power Engineering (Tianjin) Co., Ltd.',
    other_company3_address: 'Room 1134, Huaying Building, Central Avenue, Tianjin Pilot Free Trade Zone (Airport Economic Zone)',
    address: "address",
    email: "Mail",
    phone: "Telephone",
    language: 'language',
    confirm: "confirm",
    cancel: "cancel",
    explo_road: "Development Path",
    road1: "C & S IKE Group invests in Jiangsu SunMae Photovoltaic Technology Co., Ltd.",
    road2: "Signed a dual power supply renovation project for seismic station monitoring with the Tianjin Seismological Bureau to realize the complementarity of mains power and photovoltaic power generation monitored by the seismic station and ensure the normal operation of the seismic station monitoring",
    road3: "Signed a 20MW power station supporting contract with CNNC (Nanjing) Energy Development Company, and the company started large-scale ground power station business",
    road4: "Achieved photovoltaic product supply cooperation with China Electronics (India) New Energy Co., Ltd. to provide supporting products for 23MW power stations",
    road5: "According to the business needs of the power station, Xuzhou Zhongwei Human Resources Co., Ltd. was established to provide guarantee for the construction of photovoltaic power stations and power engineering contracting business",
    road6: "According to the business needs of the power station, Xinneng Electric Power Engineering (Tianjin) Company was established to provide guarantee for the construction of photovoltaic power stations and power engineering contracting business",
    road7: "As of August 2023, the total installed capacity of photovoltaic power station projects undertaken or supported by the company is 315MW",
    year: 'year',
    month: 'month',
    load_more: 'load more',
    dz_ys: "Advantages",
    company_name: 'Sunmae',
    company_sub: "光伏节能建筑、光伏电站和储能运营商",
    company_intro_content: "江苏鑫美光伏科技有限公司隶属于C&S IKE集团，于2017年成立。公司总部位于淮海经济区的核心城市江苏省徐州市。公司专注光伏电站和储能项目的全球开发、投资、建设与运维管理，融汇母公司C&S IKE集团的雄厚支持，致力于分布式光伏电站和储能建设，为全球能源革命和绿色城市建设贡献力量"
}