export default {
    about: '关于鑫美',
    product: '产品中心',
    service: '技术服务',
    download: '下载中心',
    concact: '联系我们',
    support:"技术支持：江苏雪球软件",
    follow_us:"关注我们",
    company_address:"江苏省徐州市云龙区万达广场3-911",
    componany_controducation:"公司简介",
    all_world:"全球分布",
    news_center:'新闻中心',
    guangfu_power:'光伏电站',
    power_system:'储能系统',
    sun_no_limit:"太阳能创新，能量无界",
    no_limit_tomorrow:"创新科技驱动，引领太阳能革命，开创能量无限的明天",
    know_xm:'了解鑫美',
    sun_with:"智慧能源，太阳相伴",
    sun_road:"在可持续发展的道路上，以智慧能源为引航，让太阳的光芒永恒相伴",
    know_gfdz:"了解光伏电站",
    feture_solution:"储能未来：为能源挑战提供创新性解决方案",
    feture_solution_sub:"储能科技演进：从电池到热储，多元选择引领能源革命",
    know_cnxt:'了解储能系统',
    settle_servie:"定制解决方案，尽享优质服务",
    settle_servie_sub:"驾驭太阳的力量，为您量身打造绿色能源未来",
    settle_servie_btn:"了解服务",
    key_feture:"资料库，探索能源未来的钥匙",
    key_feture_sub:"透过资料的洞察，揭示引领未来能源之门的智慧密码",
    key_feture_btn:"下载中心",
    create_way:"沟通与合作：连接能源创新之路",
    create_way_sub:"专业团队为您提供个性化服务，您可以通过以下方式与我们取得联系",
    create_way_btn:"联系我们"
}