export default {
    about: '关于鑫美',
    product: '产品中心',
    service: '技术服务',
    download: '下载中心',
    concact: '联系我们',
    support: "技术支持：江苏雪球软件",
    follow_us: "关注我们",
    company_address: "江苏省徐州市云龙区万达广场3-911",
    componany_controducation: "公司简介",
    all_world: "全球分布",
    news_center: '新闻中心',
    guangfu_power: '光伏电站',
    power_system: '储能系统',
    sun_no_limit: "太阳能创新，能量无界",
    no_limit_tomorrow: "创新科技驱动，引领太阳能革命，开创能量无限的明天",
    know_xm: '了解鑫美',
    sun_with: "智慧能源，太阳相伴",
    sun_road: "在可持续发展的道路上，以智慧能源为引航，让太阳的光芒永恒相伴",
    know_gfdz: "了解光伏电站",
    feture_solution: "储能未来：为能源挑战提供创新性解决方案",
    feture_solution_sub: "储能科技演进：从电池到热储，多元选择引领能源革命",
    know_cnxt: '了解储能系统',
    settle_servie: "定制解决方案，尽享优质服务",
    settle_servie_sub: "驾驭太阳的力量，为您量身打造绿色能源未来",
    settle_servie_btn: "了解服务",
    key_feture: "资料库，探索能源未来的钥匙",
    key_feture_sub: "透过资料的洞察，揭示引领未来能源之门的智慧密码",
    key_feture_btn: "下载中心",
    create_way: "沟通与合作：连接能源创新之路",
    create_way_sub: "专业团队为您提供个性化服务，您可以通过以下方式与我们取得联系",
    create_way_btn: "联系我们",
    ten_year: "10 年+",
    experise: "经验",
    one_wish: "一个愿景",
    Mwall: '兆瓦',
    amount_machain: "总装机量",
    company_intro: "公司介绍",
    first_intro: "江苏鑫美光伏科技有限公司隶属于备受瞩目的欧洲C&S IKE集团，于2017年成立。公司总部位于徐州市，坐落于淮海经济区的核心城市。我们以创新引领，专注光伏电站和储能项目的全球开发、投资、建设与运维管理，遍布多国，融汇母公司C&S IKE集团的雄厚支持，致力于塑造分布式电站和储能项目的未来，为全球能源革命和绿色城市建设贡献力量。",
    second_intro: '拥有独具慧眼的团队成员，积淀超过10年的行业智慧，公司掌握着光伏电站和储能项目的精髓。依托精湛的设计、高效的施工以及卓越的后期运维，我们坚守可靠与安全的承诺，确保每个光伏电站和储能项目持续高效运转。',
    thirs_intro: "我们的愿景是向全球呈现纯净、高效、安全的光伏力量，为合作伙伴创造卓越回报，燃烧激情，推动全球绿色能源的腾飞。在光伏电站和储能领域，我们秉持创新与奉献，立志在可再生能源领域书写崭新篇章，为可持续发展赋予更光辉的色彩。",
    forward: "领先的",
    high_product: "高性能产品",
    one_body: "一体化",
    poduct_map: "产业布局",
    gf_expreise: "光伏行业经验",
    authority: "权威",
    responity_sg: "施工资质保障",
    fast: "快速",
    recall_service: "响应服务",
    global_map: "全球布局",
    blobal_details: "江苏鑫美光伏科技有限公司，实力雄厚，资金充足，售后服务卓越。倚靠C&S IKE集团公司的雄厚资金和技术优势，我们的业务蓬勃发展，全球版图无限辉煌。业务遍及100多个国家和地区，其中公司在欧洲希腊、中国上海、徐州、合肥和天津设立公司。这一布局既是我们实力的体现，更是我们在全球和全国范围内为客户提供卓越光伏解决方案的承诺。",
    partener: "合作伙伴",
    news_desc: "鑫美官方发布的最新动态或消息，为您提供关于鑫美光伏的第一手资讯",
    investment_value: "投资价值",
    investment_value_content: "电费折扣、售电收入、政策补贴、碳交易等多重收益，高收益高回报",
    safe_reliable: "安全可靠",
    safe_reliable_content: "为当地政府贡献税收，为当地解决人员就业，为当地百姓带来土地收入",
    power_rationing: "缓解限电",
    power_rationing_content: "缓解高耗能企业用电紧张问题的同时，还有效规避了集中式电站常常面临的资源浪费和限电问题",
    emission_reduction: "环保减排",
    emission_reduction_content: "1MW 分布式，每年发电约120万度，相当等于节约标准煤350吨，减少二氧化碳排放1000吨",
    energie_trends: "能源趋势",
    energie_trends_content: "解决全球能源与碳排放问题的趋势，国际贸易环境下的绿色供应链管理优势",
    stable_electricity: "稳定用电",
    stable_electricity_content: "有效规避了未来电价上涨可能带来的负面影响，为企业的生产运营和财务健康提供了有力的支持",
    gfdz_intro: "光伏电站是一种大规模利用太阳能光伏技术发电的设施，它通常由大量太阳能电池板组成，用于将太阳光转化为电能。这些电池板通过光伏效应，将太阳能转化为直流电流，然后经过逆变器转换为交流电，以便连接到电力网络供应能源。光伏电站在能源领域扮演着重要角色，可以为社会供应清洁的、可再生的电能，减少对化石燃料的依赖，降低温室气体排放，推动可持续发展和环保目标的实现。",
    installed_area: "已安装地区",
    partener_company: '合作公司',

}