export default {
    about: '关于鑫美',
    product: '产品中心',
    service: '技术服务',
    download: '下载中心',
    concact: '联系我们',
    support: "技术支持：江苏雪球软件",
    follow_us: "关注我们",
    company_address: "江苏省徐州市经济技术开发区龙湖东路6号",
    componany_controducation: "公司简介",
    all_world: "全球分布",
    news_center: '新闻中心',
    guangfu_power: '光伏电站',
    power_system: '储能系统',
    sun_no_limit: "太阳能创新，能量无界",
    no_limit_tomorrow: "创新科技驱动，引领太阳能革命，开创能量无限的明天",
    know_xm: '了解鑫美',
    sun_with: "智慧能源，太阳相伴",
    sun_road: "在可持续发展的道路上，以智慧能源为引航，让太阳的光芒永恒相伴",
    know_gfdz: "了解光伏电站",
    feture_solution: "储能未来：为能源挑战提供创新性解决方案",
    feture_solution_sub: "储能科技演进：从电池到热储，多元选择引领能源革命",
    know_cnxt: '了解储能系统',
    settle_servie: "定制解决方案，尽享优质服务",
    settle_servie_sub: "驾驭太阳的力量，为您量身打造绿色能源未来",
    settle_servie_btn: "了解服务",
    key_feture: "资料库，探索能源未来的钥匙",
    key_feture_sub: "透过资料的洞察，揭示引领未来能源之门的智慧密码",
    key_feture_btn: "下载中心",
    create_way: "沟通与合作：连接能源创新之路",
    create_way_sub: "专业团队为您提供个性化服务，您可以通过以下方式与我们取得联系",
    create_way_btn: "联系我们",
    ten_year: "10 年+",
    experise: "经验",
    one_wish: "一个愿景",
    Mwall: '兆瓦',
    amount_machain: "总装机量",
    company_intro: "公司介绍",
    first_intro: "江苏鑫美光伏科技有限公司隶属于C&S IKE集团，于2017年成立。公司总部位于淮海经济区的核心城市江苏省徐州市。公司专注光伏电站和储能项目的全球开发、投资、建设与运维管理，融汇母公司C&S IKE集团的雄厚支持，致力于分布式光伏电站和储能建设，为全球能源革命和绿色城市建设贡献力量。",
    second_intro: '团队成员积淀超过10年的行业经验，掌握着光伏电站和储能项目的精髓。依托精湛的设计、高效的施工以及卓越的后期运维，确保每个光伏电站和储能项目持续高效运转。',
    thirs_intro: "我们的愿景是向全球呈现高效、安全的绿色电力，为合作伙伴创造卓越回报",
    forward: "领先的",
    high_product: "高性能产品",
    one_body: "一体化",
    poduct_map: "产业布局",
    gf_expreise: "光伏行业经验",
    authority: "权威",
    responity_sg: "施工资质保障",
    fast: "快速",
    recall_service: "响应服务",
    global_map: "全球布局",
    blobal_details: "江苏鑫美光伏科技有限公司。依靠C&S IKE集团公司的雄厚资金和技术优势。业务遍及30多个国家和地区，其中公司在欧洲希腊、中国上海、徐州、合肥和天津设立公司。",
    partener: "合作伙伴",
    news_desc: "鑫美官方发布的最新动态或消息，为您提供关于鑫美光伏的第一手资讯",
    investment_value: "投资价值",
    investment_value_content: "电费折扣、售电收入、政策补贴、碳交易等多重收益，高收益高回报",
    safe_reliable: "安全可靠",
    safe_reliable_content: "为当地政府贡献税收，为当地解决人员就业，为当地百姓带来土地收入",
    power_rationing: "缓解限电",
    power_rationing_content: "缓解高耗能企业用电紧张问题的同时，还有效规避了集中式电站常常面临的资源浪费和限电问题",
    emission_reduction: "环保减排",
    emission_reduction_content: "1MW 分布式，每年发电约110万度，相当等于节约标准煤350吨，减少二氧化碳排放1000吨",
    energie_trends: "能源趋势",
    energie_trends_content: "解决全球能源与碳排放问题的趋势，国际贸易环境下的绿色供应链管理优势",
    stable_electricity: "稳定用电",
    stable_electricity_content: "有效规避了未来电价上涨可能带来的负面影响，为企业的生产运营和财务健康提供了有力的支持",
    gfdz_intro: "光伏电站是一种大规模利用太阳能光伏技术发电的设施，它通常由大量太阳能电池板组成，用于将太阳光转化为电能。这些电池板通过光伏效应，将太阳能转化为直流电流，然后经过逆变器转换为交流电，以便连接到电力网络供应能源。光伏电站在能源领域扮演着重要角色，可以为社会供应清洁的、可再生的电能，减少对化石燃料的依赖，降低温室气体排放，推动可持续发展和环保目标的实现。",
    installed_area: "已安装地区",
    partener_company: '合作公司',
    storage: "存储",
    storage_subtitle: "完全集成",
    watch_day: "可靠的",
    watch_day_subtitle: "全天候监控",
    soft_control: "手机端",
    soft_control_subtitle: "软件控制",
    power_system_intro: "储能系统是一种将多余的太阳能电力转化并储存起来，以便在太阳能不可用或电力需求高峰时使用的设施。这些储能系统有助于解决光伏发电的间歇性特点，使得太阳能电力能够更加稳定地供应给用户，提高能源利用效率。这样的系统可以使光伏发电更具可靠性，同时减少对传统电网的依赖。储能系统还可以在电力需求高峰时释放电力，帮助平衡电力供需关系，减少能源浪费。",
    max_value: "实现价值最大化",
    max_value_intro: "利用来源可靠、成本更低且可自我优化的软件系统保障业务安全并加快业务发展。生成并存储可持续的能源，以在需求高峰或公用电网断电期间随时使用。",
    product_special: "产品特点",
    product_special_content: "专为公用事业和大型商业项目而设计.我们的专业团队将帮助您设计一套既能够满足项目目标、又能最大程度发挥站点潜能的系统。",
    product_special1: "峰值负载抑制",
    product_special1_content: "高峰期供电，可减少所需费用",
    product_special2: "太阳能自耗",
    product_special2_content: "晚上利用存储的太阳能为企业供电",
    product_special3: "用电负荷转换",
    product_special3_content: "将能源消耗从一个时间点转移到另一个时间点，以避免支付高价",
    product_special4: "公用电网服务",
    product_special4_content: "为电网提供频率和电压支持",
    product_special5: "需求响应",
    product_special5_content: "能源需求高时响应公用事业信号，以赚取资金",
    product_special6: "微电网",
    product_special6_content: "无论有无连接电网，均可生成、存储并管理能源",
    product_special7: "备用电源",
    product_special7_content: "公用电网断电时，利用存储能量提供运营所需电力",
    service_content: "公司拥有领先的光伏技术团队，经验丰富的专业人员，以及广泛的全球布局，为客户提供卓越的技术服务，致力于为客户提供全面的光伏解决方案和优质的售后支持。无论是在光伏电站的开发、建设、运维，还是在储能项目的规划和实施，我们都以专业的知识和扎实的技术为客户提供持久可靠的服务，为客户实现可持续发展提供坚实支持。",
    watch_day_subtitle_content: "我们引以为豪的光伏技术团队，凝聚着顶尖的行业专家和经验丰富的工程人员，凭借数十亿小时的安全运行记录，确保我们的电池系统在从运输到安装的每个环节都保持着卓越的可靠性和安全性。为了确保客户始终得到最优质的服务，我们设立了网络运营中心，提供24/7全天候监控，以确保电站和储能项目的高效运行。",
    check_anytime: "APP随时查看",
    check_anytime_content: "我们提供的监控系统不仅让您能够通过电脑端随时查看项目信息，还通过手机应用程序为您提供了随时随地的便利。无论您身在何处，只需打开手机App，即可实时监测和掌握项目运行状态，获得数据分析和性能指标，为您的光伏电站和储能项目提供全方位的实时监控和管理，确保您始终掌握项目的动态，从而更加灵活和智能地管理您的能源资源。",
    hot_line: "电站红外热影像",
    hot_line_content1: "我国光伏产业在国际市场发展非常迅速,作为一种清洁能源,光伏产业的前景不可估量。但与此同时也存在很多问题,光伏电站在运作中会存在质量隐患或安全隐患，意外事故发生。红外热像仪作为一个准确、快速、可靠的太阳能电池板检查工具，可全面监控系统状态，帮助光伏电站解决故障问题。我司专门购买了大疆Mavic 3T无忧套装解决这一问题。通过优化彩色像素分布，IREdge细节增强成像可以增强图像线条的锐度，光伏组件的轮廓更加清晰。可见光测温技术在比较被测物体确认缺陷的实际位置的同时，看热像图。",
    hot_line_content2: "通过调整热像图片的透明度，可以在可见光照片的视觉状态下获取任意点的温度数据，对运维人员观察分析缺陷非常友好方便。",
    sys_authority: "机构认证",
    sys_authority_content1: "IEC61701,IEC62716, IEC60068",
    sys_authority_content2: "IS09001: 2015: 质量管理体系 IS014001: 2015: 环境管理体系",
    sys_authority_content3: "IS045001: 2018: 职业健康和安全管理系统",
    download_desc: "您可以找到关于收资清单技术部分和资信部分等文档，以便了解更多信息",
    concact_desc: "您可以通过以下方式与鑫美光伏取得联系",
    table_number: "序号",
    material_name: "材料名称",
    material_type: "材料类型",
    material_use: "说明/用途",
    main_company: "中国公司总部",
    main_company_name: "江苏鑫美光伏科技有限公司",
    main_company_address: "江苏省徐州市经济开发区龙湖东路6号金龙湖创新谷",
    other_company1: '母公司',
    other_company1_name: 'WANG O.E. "ELECTRIC POWER PATRAS"',
    other_company1_address: 'N.E.O. Patron - Athinon 74, Patra 264 42',
    other_company2: '上海公司',
    other_company2_name: '上海巴适克能源科技有限公司',
    other_company2_address: '上海市杨浦区国权北路1688弄68号1303室',
    other_company3: '天津分公司',
    other_company3_name: '鑫能电力工程（天津）有限公司',
    other_company3_address: '天津自贸试验区（空港经济区）中心大道华盈大厦1134',
    address: "地址",
    email: "邮箱",
    phone: "电话",
    language: '语言',
    confirm: '确定',
    cancel: '取消',
    explo_road: "发展历程",
    road1: "C&S IKE集团投资江苏鑫美光伏科技有限公司",
    road2: "与天津地震局签订地震台监控双电源供电改造项目，实现地震台监测的市电和光伏发电互补，保证地震台监测的正常运行",
    road3: "与中核集团（南京）能源发展公司签订20MW电站配套合同，公司开始大型地面电站业务",
    road4: "与中电科(印度)新能源有限公司达成光伏产品供应合作，提供23MW电站配套产品",
    road5: "根据电站业务需要，成立徐州中伟人力资源有限公司，为光伏电站施工和电力工程承包业务提供保障",
    road6: "根据电站业务需要，成立鑫能电力工程（天津）公司，为光伏电站施工和电力工程承包业务提供保障",
    road7: "截止2023年8月公司承建或配套光伏电站项目总装机量为315MW",
    year: '年',
    month: '月',
    load_more: '加载更多',
    dz_ys: "电站的优势",
    company_name: '鑫美光伏',
    company_sub: "光伏节能建筑、光伏电站和储能运营商",
    company_intro_content: "江苏鑫美光伏科技有限公司隶属于C&S IKE集团，于2017年成立。公司总部位于淮海经济区的核心城市江苏省徐州市。公司专注光伏电站和储能项目的全球开发、投资、建设与运维管理，融汇母公司C&S IKE集团的雄厚支持，致力于分布式光伏电站和储能建设，为全球能源革命和绿色城市建设贡献力量"
}